# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty #local
#prod:permalink:        /:year/:month/:title

# Setup
title:            g3rv4
tagline:          'Gervasio Marchand'
description:      'A blog sporadically written by a <i>very</i> <strike>lucky</strike> passionate nerd'
meta_description: "Welcome to my blog. I'm Gervasio, currently working as a developer at Stack Overflow. I'm a nerd that loves doing nerdy stuff (unless it involves nerd movies)"
meta_tags:        ['blog', 'nerd', 'gervasio marchand', 'programming']
url:              https://g3rv4.com
baseurl:          /
analytics_id:     UA-63055108-3

name:             Gervasio Marchand

twitter_username: g3rv4
stack_url:        https://stackoverflow.com/users/920295/g3rv4
author_image:     public/images/g3rv4.jpg
logo:             public/images/g3rv4.jpg

paginate:         300
excerpt_separator: <!--more-->

extlinks:
  attributes: {rel: nofollow, target: _blank}
  check_links: false #local
#prod:  check_links: true
  check_exclude: ['twitter.com', 'youtu.be', 'onchro.me']
  rel_exclude: ['refined.chat', 'onchro.me']

build_only_this:
  enabled: true #local

#prod:sass:
#prod:  style: compressed

gems:
  - jekyll-paginate
#prod:  - octopress-minify-html

exclude:
  - "*.sh"
